# -*- coding: utf-8 -*-
"""Week9 Hw

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gP-GPAfieUMuKOipc7677-ROREZUtT4h

##Install
"""




# Commented out IPython magic to ensure Python compatibility.
# %%writefile movie_dashboard.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# from datetime import datetime
# import random
# 
# # ─── Page Config ───────────────────────────────────────────────────────────────
# st.set_page_config(
#     page_title="🎬 CinemaVault Dashboard",
#     page_icon="🎬",
#     layout="wide",
#     initial_sidebar_state="expanded",
# )
# 
# # ─── Custom CSS ────────────────────────────────────────────────────────────────
# st.markdown("""
# <style>
#   @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=DM+Sans:wght@300;400;500&display=swap');
# 
#   /* ── Global reset ── */
#   html, body, [class*="css"] {
#     font-family: 'DM Sans', sans-serif;
#     background-color: #0d0d14;
#     color: #e8e0d5;
#   }
# 
#   /* ── Main background ── */
#   .stApp {
#     background: linear-gradient(135deg, #0d0d14 0%, #12101e 60%, #0a1520 100%);
#   }
# 
#   /* ── Sidebar ── */
#   [data-testid="stSidebar"] {
#     background: linear-gradient(180deg, #13111f 0%, #0e1a2a 100%);
#     border-right: 1px solid #2a2540;
#   }
#   [data-testid="stSidebar"] * { color: #ddd6cc !important; }
# 
#   /* ── Title ── */
#   .dash-title {
#     font-family: 'Playfair Display', serif;
#     font-size: 3rem;
#     font-weight: 900;
#     background: linear-gradient(90deg, #f5c518, #e8956d, #c96baf);
#     -webkit-background-clip: text;
#     -webkit-text-fill-color: transparent;
#     letter-spacing: -1px;
#     margin-bottom: 0;
#   }
#   .dash-sub {
#     font-size: 0.95rem;
#     color: #8a8299;
#     letter-spacing: 3px;
#     text-transform: uppercase;
#     margin-top: 0;
#   }
# 
#   /* ── Metric cards ── */
#   .metric-card {
#     background: linear-gradient(135deg, #1a1730 0%, #141228 100%);
#     border: 1px solid #2e2a45;
#     border-radius: 16px;
#     padding: 22px 24px;
#     text-align: center;
#     transition: transform 0.2s ease, box-shadow 0.2s ease;
#   }
#   .metric-card:hover {
#     transform: translateY(-3px);
#     box-shadow: 0 8px 32px rgba(245, 197, 24, 0.12);
#   }
#   .metric-emoji { font-size: 2rem; }
#   .metric-val {
#     font-family: 'Playfair Display', serif;
#     font-size: 2rem;
#     font-weight: 700;
#     color: #f5c518;
#   }
#   .metric-label { font-size: 0.78rem; color: #8a8299; text-transform: uppercase; letter-spacing: 2px; }
# 
#   /* ── Section headers ── */
#   .section-hdr {
#     font-family: 'Playfair Display', serif;
#     font-size: 1.4rem;
#     color: #f5c518;
#     border-left: 4px solid #c96baf;
#     padding-left: 12px;
#     margin: 28px 0 14px;
#   }
# 
#   /* ── Sidebar form labels ── */
#   label { color: #b8b0cc !important; font-size: 0.85rem !important; }
# 
#   /* ── Input fields ── */
#   input, textarea, select, .stSelectbox, .stTextInput input, .stNumberInput input {
#     background: #1e1b30 !important;
#     border: 1px solid #3a3555 !important;
#     color: #e8e0d5 !important;
#     border-radius: 10px !important;
#   }
# 
#   /* ── Buttons ── */
#   .stButton > button {
#     background: linear-gradient(90deg, #f5c518, #e8956d) !important;
#     color: #0d0d14 !important;
#     font-weight: 700 !important;
#     border: none !important;
#     border-radius: 10px !important;
#     padding: 0.6rem 1.4rem !important;
#     letter-spacing: 0.5px !important;
#     transition: opacity 0.2s !important;
#   }
#   .stButton > button:hover { opacity: 0.88 !important; }
# 
#   /* ── Dataframe ── */
#   .stDataFrame { border-radius: 14px; overflow: hidden; }
#   [data-testid="stDataFrame"] th {
#     background: #1e1b30 !important;
#     color: #f5c518 !important;
#     font-family: 'DM Sans', sans-serif !important;
#     font-weight: 500 !important;
#     letter-spacing: 1px !important;
#   }
# 
#   /* ── Divider ── */
#   hr { border-color: #2a2540 !important; }
# 
#   /* ── Scrollbar ── */
#   ::-webkit-scrollbar { width: 6px; }
#   ::-webkit-scrollbar-track { background: #0d0d14; }
#   ::-webkit-scrollbar-thumb { background: #3a3555; border-radius: 4px; }
# 
#   /* ── Search box ── */
#   .stTextInput > div > div > input { background: #1a1730 !important; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ─── Seed Data ─────────────────────────────────────────────────────────────────
# DEFAULT_MOVIES = [
#     {"title": "Metropolis",          "filmmaker": "Fritz Lang",           "year": 1927, "genre": "Sci-Fi",    "medium": "35mm Film",     "price": 18.00, "attendance": 1840, "era": "Silent Era"},
#     {"title": "Citizen Kane",        "filmmaker": "Orson Welles",         "year": 1941, "genre": "Drama",     "medium": "35mm Film",     "price": 22.00, "attendance": 3200, "era": "Golden Age"},
#     {"title": "Rashomon",            "filmmaker": "Akira Kurosawa",       "year": 1950, "genre": "Drama",     "medium": "35mm Film",     "price": 20.00, "attendance": 2900, "era": "Golden Age"},
#     {"title": "Vertigo",             "filmmaker": "Alfred Hitchcock",     "year": 1958, "genre": "Thriller",  "medium": "35mm Film",     "price": 24.00, "attendance": 4100, "era": "Golden Age"},
#     {"title": "8½",                  "filmmaker": "Federico Fellini",     "year": 1963, "genre": "Drama",     "medium": "35mm Film",     "price": 21.00, "attendance": 2600, "era": "New Wave"},
#     {"title": "2001: A Space Odyssey","filmmaker": "Stanley Kubrick",     "year": 1968, "genre": "Sci-Fi",    "medium": "70mm Film",     "price": 28.00, "attendance": 5200, "era": "New Wave"},
#     {"title": "Chinatown",           "filmmaker": "Roman Polanski",       "year": 1974, "genre": "Noir",      "medium": "35mm Film",     "price": 23.00, "attendance": 3800, "era": "New Hollywood"},
#     {"title": "Apocalypse Now",      "filmmaker": "Francis Ford Coppola", "year": 1979, "genre": "War",       "medium": "70mm Film",     "price": 26.00, "attendance": 4500, "era": "New Hollywood"},
#     {"title": "Blade Runner",        "filmmaker": "Ridley Scott",         "year": 1982, "genre": "Sci-Fi",    "medium": "35mm Film",     "price": 25.00, "attendance": 4800, "era": "New Hollywood"},
#     {"title": "Blue Velvet",         "filmmaker": "David Lynch",          "year": 1986, "genre": "Mystery",   "medium": "35mm Film",     "price": 22.00, "attendance": 2200, "era": "New Hollywood"},
#     {"title": "Pulp Fiction",        "filmmaker": "Quentin Tarantino",    "year": 1994, "genre": "Crime",     "medium": "35mm Film",     "price": 27.00, "attendance": 6100, "era": "Modern"},
#     {"title": "Fargo",               "filmmaker": "Coen Brothers",        "year": 1996, "genre": "Crime",     "medium": "35mm Film",     "price": 24.00, "attendance": 3900, "era": "Modern"},
#     {"title": "Mulholland Drive",    "filmmaker": "David Lynch",          "year": 2001, "genre": "Mystery",   "medium": "Digital",       "price": 20.00, "attendance": 2700, "era": "Modern"},
#     {"title": "There Will Be Blood", "filmmaker": "Paul Thomas Anderson",  "year": 2007, "genre": "Drama",    "medium": "Digital",       "price": 23.00, "attendance": 3300, "era": "Modern"},
#     {"title": "Parasite",            "filmmaker": "Bong Joon-ho",         "year": 2019, "genre": "Thriller",  "medium": "Digital 4K",    "price": 30.00, "attendance": 7200, "era": "Contemporary"},
#     {"title": "Tár",                 "filmmaker": "Todd Field",           "year": 2022, "genre": "Drama",     "medium": "Digital 4K",    "price": 29.00, "attendance": 4100, "era": "Contemporary"},
# ]
# 
# # ─── Session State ──────────────────────────────────────────────────────────────
# if "movies" not in st.session_state:
#     st.session_state.movies = DEFAULT_MOVIES.copy()
# 
# # ─── Sidebar: Add Movie ─────────────────────────────────────────────────────────
# with st.sidebar:
#     st.markdown("## 🎬 CinemaVault")
#     st.markdown("<p style='color:#8a8299;font-size:0.8rem;'>Curated Film Collection</p>", unsafe_allow_html=True)
#     st.divider()
# 
#     st.markdown("### ➕ Add New Film")
# 
#     title      = st.text_input("🎞️ Film Title", placeholder="e.g. The Seventh Seal")
#     filmmaker  = st.text_input("🎥 Filmmaker", placeholder="e.g. Ingmar Bergman")
#     year       = st.number_input("📅 Year", min_value=1888, max_value=datetime.now().year, value=2000, step=1)
#     genre      = st.selectbox("🎭 Genre", ["Drama", "Sci-Fi", "Thriller", "Crime", "Horror", "Romance", "War", "Comedy", "Mystery", "Noir", "Animation", "Documentary", "Other"])
#     medium     = st.selectbox("📽️ Medium", ["35mm Film", "70mm Film", "Digital", "Digital 4K", "IMAX", "16mm Film", "VHS Restoration", "Nitrate Print"])
#     era        = st.selectbox("🕰️ Cinema Era", ["Silent Era", "Golden Age", "New Wave", "New Hollywood", "Modern", "Contemporary"])
#     price      = st.number_input("💰 Ticket Price ($)", min_value=1.0, max_value=200.0, value=25.0, step=0.5)
#     attendance = st.number_input("👥 Attendance", min_value=0, max_value=100000, value=3000, step=100)
# 
#     st.markdown("")
#     if st.button("🎬 Add to Collection", use_container_width=True):
#         if title.strip() and filmmaker.strip():
#             st.session_state.movies.append({
#                 "title": title.strip(),
#                 "filmmaker": filmmaker.strip(),
#                 "year": int(year),
#                 "genre": genre,
#                 "medium": medium,
#                 "price": float(price),
#                 "attendance": int(attendance),
#                 "era": era,
#             })
#             st.success(f"✅ **{title}** added to the vault!")
#             st.balloons()
#         else:
#             st.error("Please fill in Title and Filmmaker.")
# 
#     st.divider()
#     if st.button("🔄 Reset to Defaults", use_container_width=True):
#         st.session_state.movies = DEFAULT_MOVIES.copy()
#         st.rerun()
# 
# # ─── Main Area ──────────────────────────────────────────────────────────────────
# df = pd.DataFrame(st.session_state.movies)
# 
# # Header
# st.markdown('<p class="dash-title">🎬 CinemaVault</p>', unsafe_allow_html=True)
# st.markdown('<p class="dash-sub">✦ Curated Cinematic Archive ✦</p>', unsafe_allow_html=True)
# st.markdown("")
# 
# # ── KPI Metrics ────────────────────────────────────────────────────────────────
# c1, c2, c3, c4, c5 = st.columns(5)
# metrics = [
#     ("🎞️", len(df), "Films"),
#     ("🎥", df["filmmaker"].nunique(), "Filmmakers"),
#     ("👥", f"{df['attendance'].sum():,}", "Total Viewers"),
#     ("💰", f"${df['price'].mean():.2f}", "Avg. Ticket"),
#     ("🏆", str(df.loc[df["attendance"].idxmax(), "year"]) if not df.empty else "—", "Best Year"),
# ]
# for col, (emoji, val, label) in zip([c1, c2, c3, c4, c5], metrics):
#     with col:
#         st.markdown(f"""
#         <div class="metric-card">
#           <div class="metric-emoji">{emoji}</div>
#           <div class="metric-val">{val}</div>
#           <div class="metric-label">{label}</div>
#         </div>""", unsafe_allow_html=True)
# 
# st.markdown("")
# 
# # ── Charts Row ────────────────────────────────────────────────────────────────
# left, right = st.columns([3, 2])
# 
# with left:
#     st.markdown('<div class="section-hdr">📊 Attendance by Film</div>', unsafe_allow_html=True)
#     chart_df = df.nlargest(12, "attendance").sort_values("attendance")
#     fig_bar = go.Figure(go.Bar(
#         x=chart_df["attendance"],
#         y=chart_df["title"],
#         orientation="h",
#         marker=dict(
#             color=chart_df["attendance"],
#             colorscale=[[0, "#3a2060"], [0.4, "#c96baf"], [0.7, "#e8956d"], [1.0, "#f5c518"]],
#             showscale=False,
#         ),
#         text=[f"  {v:,}" for v in chart_df["attendance"]],
#         textposition="outside",
#         textfont=dict(color="#e8e0d5", size=11),
#         hovertemplate="<b>%{y}</b><br>Viewers: %{x:,}<extra></extra>",
#     ))
#     fig_bar.update_layout(
#         plot_bgcolor="rgba(0,0,0,0)",
#         paper_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="DM Sans", color="#a09aaa"),
#         xaxis=dict(showgrid=False, showticklabels=False, zeroline=False),
#         yaxis=dict(gridcolor="rgba(255,255,255,0.04)", tickfont=dict(size=12, color="#ddd6cc")),
#         margin=dict(l=0, r=60, t=10, b=10),
#         height=380,
#     )
#     st.plotly_chart(fig_bar, use_container_width=True)
# 
# with right:
#     st.markdown('<div class="section-hdr">🎭 Genre Distribution</div>', unsafe_allow_html=True)
#     genre_counts = df["genre"].value_counts().reset_index()
#     genre_counts.columns = ["genre", "count"]
#     PALETTE = ["#f5c518","#e8956d","#c96baf","#7b62d4","#4fa8d8","#5dcea0","#f06060","#a0c96b","#d48b2a","#8888cc"]
#     fig_pie = go.Figure(go.Pie(
#         labels=genre_counts["genre"],
#         values=genre_counts["count"],
#         hole=0.52,
#         marker=dict(colors=PALETTE[:len(genre_counts)], line=dict(color="#0d0d14", width=3)),
#         textinfo="label+percent",
#         textfont=dict(size=11, color="#e8e0d5"),
#         hovertemplate="<b>%{label}</b><br>%{value} films (%{percent})<extra></extra>",
#     ))
#     fig_pie.update_layout(
#         plot_bgcolor="rgba(0,0,0,0)",
#         paper_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="DM Sans", color="#a09aaa"),
#         legend=dict(font=dict(size=10, color="#b8b0cc"), bgcolor="rgba(0,0,0,0)"),
#         margin=dict(l=0, r=0, t=10, b=10),
#         height=380,
#         annotations=[dict(text="🎬", font=dict(size=28), showarrow=False)],
#     )
#     st.plotly_chart(fig_pie, use_container_width=True)
# 
# # ── Era Bubble Chart ───────────────────────────────────────────────────────────
# st.markdown('<div class="section-hdr">🕰️ Films Through Time</div>', unsafe_allow_html=True)
# ERA_COLORS = {
#     "Silent Era": "#f5c518", "Golden Age": "#e8956d", "New Wave": "#c96baf",
#     "New Hollywood": "#7b62d4", "Modern": "#4fa8d8", "Contemporary": "#5dcea0",
# }
# fig_time = px.scatter(
#     df, x="year", y="attendance", size="price",
#     color="era", color_discrete_map=ERA_COLORS,
#     hover_name="title",
#     hover_data={"filmmaker": True, "genre": True, "year": True, "attendance": True, "price": True, "era": False},
#     size_max=40,
#     labels={"year": "Year", "attendance": "Attendance", "era": "Era"},
# )
# fig_time.update_layout(
#     plot_bgcolor="rgba(0,0,0,0)",
#     paper_bgcolor="rgba(0,0,0,0)",
#     font=dict(family="DM Sans", color="#a09aaa"),
#     xaxis=dict(gridcolor="rgba(255,255,255,0.05)", zeroline=False, tickfont=dict(color="#b8b0cc")),
#     yaxis=dict(gridcolor="rgba(255,255,255,0.05)", zeroline=False, tickfont=dict(color="#b8b0cc")),
#     legend=dict(font=dict(color="#b8b0cc"), bgcolor="rgba(0,0,0,0)", bordercolor="rgba(0,0,0,0)"),
#     margin=dict(l=0, r=0, t=10, b=10),
#     height=300,
# )
# fig_time.update_traces(marker=dict(line=dict(width=1.5, color="#0d0d14")))
# st.plotly_chart(fig_time, use_container_width=True)
# 
# # ── Film Table with Search ─────────────────────────────────────────────────────
# st.markdown('<div class="section-hdr">🗂️ Film Archive</div>', unsafe_allow_html=True)
# 
# search = st.text_input("🔍 Search by filmmaker or title…", placeholder="e.g. Kubrick, Hitchcock, Parasite…")
# 
# display_df = df.copy()
# if search.strip():
#     mask = (
#         display_df["title"].str.contains(search, case=False, na=False) |
#         display_df["filmmaker"].str.contains(search, case=False, na=False)
#     )
#     display_df = display_df[mask]
#     if display_df.empty:
#         st.warning(f"🔎 No films found matching **'{search}'**")
# 
# if not display_df.empty:
#     # Style and rename for display
#     show = display_df[["title", "filmmaker", "year", "genre", "era", "medium", "price", "attendance"]].copy()
#     show = show.sort_values("attendance", ascending=False).reset_index(drop=True)
#     show.index = show.index + 1
#     show.columns = ["🎞️ Title", "🎥 Filmmaker", "📅 Year", "🎭 Genre", "🕰️ Era", "📽️ Medium", "💰 Price ($)", "👥 Attendance"]
# 
#     st.dataframe(
#         show,
#         use_container_width=True,
#         height=min(40 + 38 * len(show), 520),
#         column_config={
#             "💰 Price ($)": st.column_config.NumberColumn(format="$%.2f"),
#             "👥 Attendance": st.column_config.NumberColumn(format="%d"),
#         }
#     )
#     st.markdown(f"<p style='color:#6a6480;font-size:0.8rem;text-align:right;'>Showing {len(show)} of {len(df)} films</p>", unsafe_allow_html=True)
# 
# # ── Footer ─────────────────────────────────────────────────────────────────────
# st.divider()
# st.markdown("<p style='text-align:center;color:#3a3555;font-size:0.78rem;'>🎬 CinemaVault Dashboard &nbsp;|&nbsp; Built with Streamlit &amp; Plotly &nbsp;|&nbsp; ✦ For the love of cinema ✦</p>", unsafe_allow_html=True)

"""## Run"""

import subprocess, time

subprocess.Popen(
    ["streamlit", "run", "movie_dashboard.py",
     "--server.port=8501",
     "--server.headless=true",
     "--server.enableCORS=false",
     "--server.enableXsrfProtection=false"]
)

print("Streamlit 시작 대기중...")
time.sleep(10)  # ← 5초→10초로 늘림
print("완료!")

!curl -s https://ipv4.icanhazip.com

!lt --port 8501
